// Generated by scripts/generate-device-fixtures.mjs. Do not edit.
#pragma once
#include "apple/game_state/types.hpp"
#include <vector>
#include <string>
namespace apple::firmware {
struct LabFixtureFrame { std::uint32_t at_ms; game_state::CanonicalFrame frame; };
struct LabFixture { const char* id; std::uint32_t duration_ms; int expected_sequences; std::vector<LabFixtureFrame> frames; };
inline const std::vector<LabFixture>& lab_fixtures() {
  using namespace game_state;
  static const std::vector<LabFixture> values = [] {
    std::vector<LabFixture> list;
    { LabFixture fixture{"live", 3600, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Pitch 4 · 92.8 mph sinker";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=2; f.evidence_outs=2; f.label="LIVE"; f.last_event="Called strike three";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({1800,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211520"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Live; f.half=Half::Top; f.inning=8; f.display_outs=0; f.evidence_outs=0; f.label="LIVE"; f.last_event="Top eighth begins";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=0; a.bases={false,false,false}; a.batter="Ronald Acuña Jr."; a.batter_line="0–3"; a.pitcher="Kodai Senga"; a.pitch_count=87; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({3600,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"home-run", 43100, 1, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Pitch 4 · 92.8 mph sinker";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Juan Soto homers to right field";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",3};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.changed_plays.push_back({"777686:play-47",47,121,"Juan Soto",PlayKind::HomeRun,true,ReviewState::None});
        f.review=ReviewState::None; fixture.frames.push_back({900,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"grand-slam", 43100, 1, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Pitch 4 · 92.8 mph sinker";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=1; a.strikes=1; a.bases={true,true,true}; a.batter="Francisco Lindor"; a.batter_line="1–3"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Francisco Lindor hits a grand slam to left field";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",6};
        { AtBatState a; a.balls=1; a.strikes=1; a.bases={true,true,true}; a.batter="Francisco Lindor"; a.batter_line="1–3"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.changed_plays.push_back({"777686:play-48",48,121,"Francisco Lindor",PlayKind::GrandSlam,true,ReviewState::None});
        f.review=ReviewState::None; fixture.frames.push_back({900,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"review-confirmed", 45400, 1, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Pitch 4 · 92.8 mph sinker";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Review; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="REVIEW"; f.last_event="Potential home run under review";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",3};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.changed_plays.push_back({"777686:play-52",47,121,"Juan Soto",PlayKind::HomeRun,true,ReviewState::Pending});
        f.review=ReviewState::Pending; fixture.frames.push_back({900,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211520"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Juan Soto home run confirmed after review";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",3};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.changed_plays.push_back({"777686:play-52",47,121,"Juan Soto",PlayKind::HomeRun,true,ReviewState::Confirmed});
        f.review=ReviewState::Confirmed; fixture.frames.push_back({3200,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"review-overturned", 4600, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Potential home run under review";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::Pending; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Review; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="REVIEW"; f.last_event="Potential home run under review";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.changed_plays.push_back({"777686:play-52",47,121,"Juan Soto",PlayKind::HomeRun,true,ReviewState::Pending});
        f.review=ReviewState::Pending; fixture.frames.push_back({900,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211520"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="LIVE"; f.last_event="Foul ball after review";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.changed_plays.push_back({"777686:play-52",47,121,"Juan Soto",PlayKind::HomeRun,true,ReviewState::Overturned});
        f.review=ReviewState::Overturned; fixture.frames.push_back({2800,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"rain-delay", 3500, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Game delayed · weather";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Waiting for official update";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({3500,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"game-delay", 3500, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Delay in progress";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Waiting for official update";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({3500,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"game-suspended", 3500, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Play stopped";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Waiting for official update";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({3500,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"game-postponed", 3500, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Next game time to be determined";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Waiting for official update";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({3500,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"game-cancelled", 3500, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Schedule update pending";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_211510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Delayed; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="DELAYED"; f.last_event="Waiting for official update";
        f.away={144,"ATL","Atlanta",2}; f.home={121,"NYM","Mets",2};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({3500,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"mets-win", 43400, 1, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_221500"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Top; f.inning=9; f.display_outs=2; f.evidence_outs=2; f.label="LIVE"; f.last_event="Two outs, top ninth";
        f.away={144,"ATL","Atlanta",4}; f.home={121,"NYM","Mets",4};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_221510"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Final; f.half=Half::End; f.inning=9; f.display_outs=3; f.evidence_outs=3; f.label="FINAL"; f.last_event="Mets win! Put it in the books!";
        f.away={144,"ATL","Atlanta",4}; f.home={121,"NYM","Mets",5};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({1200,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"doubleheader", 48300, 1, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_180000"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Live; f.half=Half::Bottom; f.inning=9; f.display_outs=2; f.evidence_outs=2; f.label="LIVE"; f.last_event="Two outs, bottom ninth of Game 1";
        f.away={144,"ATL","Atlanta",4}; f.home={121,"NYM","Mets",4};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260826_180010"; f.update_mode=UpdateMode::Incremental; f.phase=Phase::Final; f.half=Half::End; f.inning=9; f.display_outs=3; f.evidence_outs=3; f.label="FINAL"; f.last_event="Mets walk off Game 1";
        f.away={144,"ATL","Atlanta",4}; f.home={121,"NYM","Mets",5};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({1200,std::move(f)}); }
      { CanonicalFrame f; f.game_pk=777687; f.game_number=2; f.cursor="20260826_220000"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Pregame; f.half=Half::Top; f.inning=1; f.display_outs=0; f.evidence_outs=0; f.label="PREGAME"; f.last_event="Game two scheduled";
        f.away={144,"ATL","Atlanta",0}; f.home={121,"NYM","Mets",0};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.scheduled_start="2026-08-26T23:10:00Z";
        f.venue="Citi Field";
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({48300,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"sleep", 0, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20260827_020000"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Sleep; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="SLEEP"; f.last_event="Low-duty schedule sleep";
        f.away={146,"MIA","Miami",0}; f.home={121,"NYM","Mets",0};
        { AtBatState a; a.balls=0; a.strikes=1; a.bases={true,true,false}; a.batter="Juan Soto"; a.batter_line="1–2"; a.pitcher="Strider"; a.pitch_count=20; f.at_bat=std::move(a); }
        f.scheduled_start="2026-08-28T23:10:00Z";
        f.venue="Citi Field";
        f.linescore.innings.push_back({1,0,0});
        f.linescore.innings.push_back({2,1,0});
        f.linescore.innings.push_back({3,0,0});
        f.linescore.innings.push_back({4,1,0});
        f.linescore.innings.push_back({5,0,1});
        f.linescore.innings.push_back({6,0,1});
        f.linescore.innings.push_back({7,0,std::nullopt});
        f.linescore.away_hits=6;
        f.linescore.home_hits=5;
        f.linescore.away_errors=0;
        f.linescore.home_errors=0;
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    { LabFixture fixture{"offseason", 0, 0, {}};
      { CanonicalFrame f; f.game_pk=777686; f.game_number=1; f.cursor="20261115_120000"; f.update_mode=UpdateMode::Bootstrap; f.phase=Phase::Sleep; f.half=Half::Bottom; f.inning=7; f.display_outs=1; f.evidence_outs=1; f.label="SLEEP"; f.last_event="The Apple is resting until baseball returns to Citi Field";
        f.away={144,"ATL","Atlanta",0}; f.home={121,"NYM","Mets",0};
        f.review=ReviewState::None; fixture.frames.push_back({0,std::move(f)}); }
      list.push_back(std::move(fixture)); }
    return list;
  }();
  return values;
}
inline const LabFixture* find_lab_fixture(const std::string& id) {
  for (const auto& f : lab_fixtures()) if (id == f.id) return &f;
  return nullptr;
}
} // namespace apple::firmware
