#pragma once

// Public half of the firmware signing key. Generated by tools/sign_firmware.py;
// the Apple refuses a wireless update whose signature this key cannot verify.
namespace apple::firmware {

constexpr char kUpdatePublicKeyPem[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/ZJ1UNh7GK476ZPf6cikQ/2nnFdh\n"
    "N2LWK/+Uvt7+5p2ZzzvV9f7tQLybYnZLIVCE0XXhNZCGPJYnw48YWKUH0Q==\n"
    "-----END PUBLIC KEY-----\n";

}  // namespace apple::firmware
