#!/usr/bin/env python3
"""Embed the Apple Manager page and logo as C++ headers.

Sources live in lib/manager/page/ (index.html, logo.png). The generated
headers are ignored by git; PlatformIO runs this before every build through
`extra_scripts`, and it can also be run by hand:

    python3 tools/embed_page.py
"""

from __future__ import annotations

import pathlib

# Under PlatformIO this file is exec'd as an extra script: no __file__, but an
# `env` with the project directory. From a shell it is an ordinary script.
try:
    Import("env")  # type: ignore[name-defined]  # noqa: F821
    ROOT = pathlib.Path(env["PROJECT_DIR"])  # type: ignore[name-defined]  # noqa: F821
except NameError:
    ROOT = pathlib.Path(__file__).resolve().parents[1]
PAGE_DIR = ROOT / "lib" / "manager" / "page"
OUT_DIR = ROOT / "lib" / "manager" / "include" / "apple" / "firmware"


def write_if_changed(path: pathlib.Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def embed() -> None:
    html = (PAGE_DIR / "index.html").read_text(encoding="utf-8")
    if ')apple"' in html:
        raise SystemExit("index.html contains the raw-string delimiter")
    page = (
        "#pragma once\n\n"
        "// Generated by tools/embed_page.py from lib/manager/page/index.html. Do not edit.\n"
        "// Edit the HTML file; PlatformIO regenerates this header before each build.\n\n"
        "namespace apple::firmware {\n\n"
        f'inline constexpr char kManagerPage[] = R"apple({html})apple";\n\n'
        "}  // namespace apple::firmware\n"
    )
    png = (PAGE_DIR / "logo.png").read_bytes()
    rows = []
    for index in range(0, len(png), 24):
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in png[index : index + 24]) + ",")
    logo = (
        "#pragma once\n\n"
        "// Generated by tools/embed_page.py from lib/manager/page/logo.png. Do not edit.\n"
        f"// {len(png)} bytes, served at /logo.png.\n\n"
        "#include <cstddef>\n\n"
        "namespace apple::firmware {\n\n"
        f"inline constexpr std::size_t kManagerLogoPngSize = {len(png)};\n"
        "inline constexpr unsigned char kManagerLogoPng[] = {\n"
        + "\n".join(rows)
        + "\n};\n\n}  // namespace apple::firmware\n"
    )
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    changed = write_if_changed(OUT_DIR / "manager_page.hpp", page)
    changed = write_if_changed(OUT_DIR / "manager_logo.hpp", logo) or changed
    print(f"manager page embedded ({len(html)} bytes html, {len(png)} bytes logo){' - updated' if changed else ''}")


embed()
