#!/usr/bin/env python3
"""Embed fixtures/mlb/*.json as C++ string literals in fixtures/mlb/fixtures.hpp.

The same captures drive the native mlb_feed tests and the Nano's built-in
replay, so a regression seen on the bench can be reproduced on the desktop.
Run it again after adding or refreshing a capture.
"""

from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1] / "fixtures" / "mlb"
OUTPUT = ROOT / "fixtures.hpp"
DELIMITER = "apple"


def main() -> None:
    lines = [
        "// Generated by tools/embed_fixtures.py from fixtures/mlb/*.json. Do not edit.",
        "#pragma once",
        "",
        "// The captures exceed the 64 KiB literal length that the C++ standard",
        "// guarantees; GCC and Clang accept them once the pedantic warning is off.",
        "#pragma GCC diagnostic push",
        "#pragma GCC diagnostic ignored \"-Woverlength-strings\"",
        "",
        "namespace apple::fixtures::mlb {",
        "",
    ]
    for path in sorted(ROOT.glob("*.json")):
        text = path.read_text(encoding="utf-8").strip()
        json.loads(text)
        if f"){DELIMITER}\"" in text:
            raise SystemExit(f"{path.name} contains the raw-string delimiter")
        name = re.sub(r"[^A-Za-z0-9]+", "_", path.stem)
        lines.append(f"// {path.name}: {len(text)} bytes")
        lines.append(f'inline constexpr char k_{name}[] = R"{DELIMITER}({text}){DELIMITER}";')
        lines.append("")
    lines.append("}  // namespace apple::fixtures::mlb")
    lines.append("")
    lines.append("#pragma GCC diagnostic pop")
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
