#!/usr/bin/env python3
"""Sign Home Run Apple firmware for wireless installs, and make the keys.

The Apple only installs a firmware file that carries a valid signature from
the project's signing key, so a corrupt download or a stranger's file never
replaces the running firmware. The signature is ECDSA P-256 over the SHA-256
of the image, appended as a fixed 96-byte trailer:

    "HRAPPLE1" (8) | version u16 LE (2) | signature length u16 LE (2) |
    reserved (12) | DER signature, zero padded (72)

Needs only the openssl command line (LibreSSL on macOS works).

    # once, keep the private key out of the public repo
    python3 tools/sign_firmware.py keygen --key ../../secrets/firmware-signing-key.pem
    python3 tools/sign_firmware.py public-key --key ../../secrets/firmware-signing-key.pem \\
        --out lib/manager/include/apple/firmware/update_public_key.hpp

    # every release
    pio run -e nano_esp32_apple
    python3 tools/sign_firmware.py sign .pio/build/nano_esp32_apple/firmware.bin \\
        --key ../../secrets/firmware-signing-key.pem --out home-run-apple-0.2.0.bin

    # check a file the way the Apple does
    python3 tools/sign_firmware.py verify home-run-apple-0.2.0.bin --public public.pem
"""
import argparse
import pathlib
import struct
import subprocess
import sys
import tempfile

MAGIC = b"HRAPPLE1"
TRAILER = 96
SIG_MAX = 72


def run(args, data=None):
    return subprocess.run(args, input=data, check=True, capture_output=True).stdout


def keygen(key: pathlib.Path):
    key.parent.mkdir(parents=True, exist_ok=True)
    pem = run(["openssl", "ecparam", "-genkey", "-name", "prime256v1", "-noout"])
    key.write_bytes(pem)
    key.chmod(0o600)
    print(f"private key written to {key} (keep it out of git)")


def public_pem(key: pathlib.Path) -> bytes:
    return run(["openssl", "ec", "-in", str(key), "-pubout"])


def write_public_header(key: pathlib.Path, out: pathlib.Path):
    pem = public_pem(key).decode()
    lines = "\n".join(f'    "{line}\\n"' for line in pem.strip().splitlines())
    out.write_text(
        "#pragma once\n\n"
        "// Public half of the firmware signing key. Generated by tools/sign_firmware.py;\n"
        "// the Apple refuses a wireless update whose signature this key cannot verify.\n"
        "namespace apple::firmware {\n\n"
        "constexpr char kUpdatePublicKeyPem[] =\n"
        f"{lines};\n\n"
        "}  // namespace apple::firmware\n"
    )
    print(f"public key header written to {out}")


def sign(image: pathlib.Path, key: pathlib.Path, out: pathlib.Path):
    data = image.read_bytes()
    if data[:1] != b"\xe9":
        sys.exit("not an ESP32 image (first byte is not 0xE9)")
    with tempfile.NamedTemporaryFile() as sig_file:
        run(["openssl", "dgst", "-sha256", "-sign", str(key), "-out", sig_file.name, str(image)])
        sig = pathlib.Path(sig_file.name).read_bytes()
    if len(sig) > SIG_MAX:
        sys.exit(f"signature too long: {len(sig)}")
    trailer = MAGIC + struct.pack("<HH", 1, len(sig)) + b"\0" * 12 + sig.ljust(SIG_MAX, b"\0")
    assert len(trailer) == TRAILER
    out.write_bytes(data + trailer)
    print(f"signed {len(data)} bytes -> {out} ({len(sig)}-byte signature)")


def verify(signed: pathlib.Path, public: pathlib.Path):
    data = signed.read_bytes()
    if len(data) < TRAILER + 1 or data[-TRAILER:][:8] != MAGIC:
        sys.exit("no Apple signature trailer")
    version, sig_len = struct.unpack("<HH", data[-TRAILER + 8:-TRAILER + 12])
    sig = data[-SIG_MAX:][:sig_len]
    image = data[:-TRAILER]
    with tempfile.NamedTemporaryFile() as img, tempfile.NamedTemporaryFile() as sig_file:
        pathlib.Path(img.name).write_bytes(image)
        pathlib.Path(sig_file.name).write_bytes(sig)
        result = subprocess.run(["openssl", "dgst", "-sha256", "-verify", str(public), "-signature", sig_file.name, img.name],
                                capture_output=True, text=True)
    ok = result.returncode == 0
    print(f"trailer v{version}, {len(image)}-byte image: {'signature OK' if ok else 'BAD SIGNATURE'}")
    sys.exit(0 if ok else 1)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    k = sub.add_parser("keygen"); k.add_argument("--key", required=True, type=pathlib.Path)
    p = sub.add_parser("public-key"); p.add_argument("--key", required=True, type=pathlib.Path); p.add_argument("--out", required=True, type=pathlib.Path)
    s = sub.add_parser("sign"); s.add_argument("image", type=pathlib.Path); s.add_argument("--key", required=True, type=pathlib.Path); s.add_argument("--out", required=True, type=pathlib.Path)
    v = sub.add_parser("verify"); v.add_argument("signed", type=pathlib.Path); v.add_argument("--public", required=True, type=pathlib.Path)
    a = ap.parse_args()
    if a.cmd == "keygen": keygen(a.key)
    elif a.cmd == "public-key": write_public_header(a.key, a.out)
    elif a.cmd == "sign": sign(a.image, a.key, a.out)
    elif a.cmd == "verify": verify(a.signed, a.public)


if __name__ == "__main__":
    main()
